# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_smc <- function(input_timeseries, input_prior, input_options) {
    .Call(`_BayesMallowsSMC2_run_smc`, input_timeseries, input_prior, input_options)
}

