# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Precompute All Topological Sorts
#'
#' This function precomputes all topological sorts for a given preference matrix and
#' saves them to a specified output directory. It ensures the output directory exists
#' and creates it if it does not.
#'
#' @param prefs An integer matrix (`arma::umat`) representing the preference relations.
#' @param n_items An integer specifying the number of items to sort.
#' @param output_directory A string specifying the directory where the output files will be saved.
#' @param max_files_to_save An integer specifying an upper limit on the number of files to save. If
#'  the number of topological sorts exceeds `max_files_to_save`, a random sample of size `max_files_to_save`
#'  is taken at random, and the corresponding sorts saved.
#'
#' @details
#' The function generates all possible topological sorts for the provided preference matrix
#' and saves each sort as a binary file in the specified output directory. The output files
#' are named sequentially as `sort0.bin`, `sort1.bin`, and so on.
#'
#' @return This function does not return a value. It performs its operations as a side effect.
#'
#' @export
precompute_topological_sorts <- function(prefs, n_items, output_directory, max_files_to_save) {
    invisible(.Call(`_BayesMallowsSMC2_precompute_topological_sorts`, prefs, n_items, output_directory, max_files_to_save))
}

run_smc <- function(input_timeseries, input_prior, input_options) {
    .Call(`_BayesMallowsSMC2_run_smc`, input_timeseries, input_prior, input_options)
}

